import { useState } from "react";
import { Download, BookOpen } from "lucide-react";
import { Cover } from "@/components/ebook/Cover";
import { Page, Ornament, PullQuote } from "@/components/ebook/Page";
import { CharacterPage } from "@/components/ebook/CharacterPage";
import { CTA } from "@/components/ebook/CTA";
import charHarley from "@/assets/char-harley.jpg";
import charRose from "@/assets/char-rose.jpg";
import charWalter from "@/assets/char-walter.jpg";
import charJordan from "@/assets/char-jordan.jpg";
import charShelby from "@/assets/char-shelby.jpg";
import charBatman from "@/assets/char-batman.jpg";
import charStrange from "@/assets/char-strange.jpg";
import charNeo from "@/assets/char-neo.jpg";

const TOTAL = 20;

export default function App() {
  const [downloading, setDownloading] = useState(false);
  const handleDownload = async () => {
    setDownloading(true);
    try {
      const html2pdf = (await import("html2pdf.js")).default;
      const el = document.getElementById("ebook-root");
      if (!el) return;
      await html2pdf().set({
        margin: 0,
        filename: "Mary-Morgan-O-Codigo-Oculto.pdf",
        image: { type: "jpeg", quality: 0.95 },
        html2canvas: { scale: 2, useCORS: true, backgroundColor: "#0A0A0A" },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      } as never).from(el).save();
    } finally { setDownloading(false); }
  };

  return <main className="relative bg-background text-foreground">
    <button onClick={handleDownload} disabled={downloading} className="no-print fixed bottom-6 right-6 z-50 inline-flex items-center gap-2 rounded-full px-5 py-3 text-[10px] tracking-[0.3em] uppercase text-[oklch(0.12_0.005_280)] shadow-2xl transition hover:scale-105 disabled:opacity-60" style={{background:"var(--gradient-gold)",boxShadow:"var(--glow-gold)"}} aria-label="Baixar ebook em PDF"><Download className="h-3.5 w-3.5" />{downloading ? "Gerando..." : "PDF"}</button>
    <div id="ebook-root">
      <Cover />
      <Page number={2} total={TOTAL} chapter="Capítulo 01" variant="dark"><h2 className="font-serif text-4xl md:text-6xl font-light leading-tight mb-10">Você Não Está Vivendo<br/><em className="text-gold">Apenas</em> o Presente.</h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Existe uma camada de você que decide antes de você decidir. Que escolhe parceiros antes da paixão. Que recusa oportunidades antes da consciência. Que repete histórias que você jurou nunca mais viver.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">O que chamamos de personalidade é, na maioria das vezes, um conjunto de defesas costuradas em silêncio — um teatro montado para sobreviver a algo que você talvez nem se lembre mais.</p><PullQuote>O presente é apenas o palco. O roteiro foi escrito muito antes.</PullQuote></Page>
      <Page number={3} total={TOTAL} chapter="Capítulo 02" variant="purple"><h2 className="font-serif text-4xl md:text-6xl font-light leading-tight mb-10">O Inconsciente<br/>Sempre Se <em className="text-gold">Disfarça</em>.</h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Ele não vem de frente. Não anuncia. Não pede licença. Ele se veste com as roupas do cotidiano: uma irritação súbita, uma escolha "irracional", uma atração que não tem explicação lógica.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">O inconsciente fala através dos seus padrões. E os padrões falam através de arquétipos — figuras universais que habitam a alma humana há milênios e que, hoje, vivem disfarçadas dentro dos personagens que mais nos comovem.</p><PullQuote>Aquilo que não trazemos à consciência aparece em nossas vidas como destino. — Carl Jung</PullQuote></Page>
      <Page number={4} total={TOTAL} chapter="Capítulo 03" variant="dark"><h2 className="font-serif text-4xl md:text-6xl font-light leading-tight mb-10">Por Que Filmes<br/>Nos <em className="text-gold">Afetam</em> Tanto?</h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Você já chorou por um personagem que nunca existiu? Já se viu defendendo o vilão? Já sentiu raiva de uma cena como se ela tivesse acontecido com você?</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Não é coincidência. Os personagens que nos atravessam carregam, na sua estrutura emocional, exatamente o material psíquico que está adormecido dentro de nós. Eles são espelhos. E o espelho não pede permissão para mostrar a verdade.</p><PullQuote>Você não se identifica com personagens. Você se reconhece neles.</PullQuote><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Nas próximas páginas, quatro arquétipos. Oito personagens. E, possivelmente, o retrato mais honesto que você já viu de si mesmo.</p></Page>
      <Page number={5} total={TOTAL} chapter="Arquétipo I" variant="purple"><p className="text-[10px] tracking-[0.5em] uppercase text-gold mb-6">Primeiro Arquétipo</p><h2 className="font-serif text-5xl md:text-7xl font-light leading-[0.95] mb-10">O Órfão<br/><em className="text-gold">Afetivo</em></h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Ele nasce do amor que faltou. Ou pior: do amor que veio condicional. É a criança que aprendeu que precisava performar para ser amada — e o adulto que ainda não desaprendeu.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">O Órfão Afetivo se apaixona por quem o ignora. Confunde caos com paixão. Acredita que precisa ser intenso o suficiente para merecer permanência. E quando alguém o ama de forma calma, ele desconfia.</p><PullQuote>Ele não busca amor. Ele busca a repetição da ferida — porque é a única coisa que reconhece como casa.</PullQuote></Page>
      <CharacterPage number={6} total={TOTAL} archetype="Órfão Afetivo" name="Harley Quinn" movie="Suicide Squad · DC" image={charHarley} quote="Eu sou aquela maluca que faz o que ninguém tem coragem de fazer." body={["Harley não é apenas caos. Harley é o que acontece quando uma mulher inteligente desiste de ser entendida e decide ser temida.","Antes de Coringa, ela era Harleen Quinzel — psiquiatra, brilhante, contida. Depois dele, virou espelho. Toda relação tóxica funciona assim: alguém entra para curar, e sai como cópia.","Ela representa o Órfão Afetivo no estágio em que a dor virou identidade. Onde o abandono não é mais inimigo: é linguagem materna."]}/>
      <CharacterPage number={7} total={TOTAL} archetype="Órfão Afetivo" name="Rose DeWitt" movie="Titanic · 1997" image={charRose} quote="Eu vejo você. Você não é nada para mim — exceto tudo." body={["Rose é o Órfão Afetivo refinado. A jaula dela tem cortinas de seda. O abandono dela não é a falta de presença — é a falta de permissão para existir como ela mesma.","Por isso ela se joga em Jack. Não por amor: por fome de respiração. Ele é o oxigênio depois de uma vida sob a água.","Toda vez que você se sente sufocado por uma vida certinha demais e quer destruir tudo de uma vez, Rose está acordando dentro de você."]}/>
      <Page number={8} total={TOTAL} chapter="Arquétipo II" variant="purple"><p className="text-[10px] tracking-[0.5em] uppercase text-gold mb-6">Segundo Arquétipo</p><h2 className="font-serif text-5xl md:text-7xl font-light leading-[0.95] mb-10">O Sobrevivente<br/>da <em className="text-gold">Escassez</em></h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Ele cresceu vendo a conta não fechar. Ouvindo brigas sobre dinheiro. Sentindo a vergonha de pedir o que precisava. E jurou — com o silêncio de uma criança — que nunca mais.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">O adulto que nasce dessa promessa não busca riqueza. Busca blindagem. Não busca conquista. Busca prova. Ele acumula para preencher um espaço que dinheiro nenhum chega.</p><PullQuote>Ele não tem ambição. Ele tem medo travestido de ambição.</PullQuote></Page>
      <CharacterPage number={9} total={TOTAL} archetype="Sobrevivente da Escassez" name="Walter White" movie="Breaking Bad · AMC" image={charWalter} quote="Eu não estou em perigo. Eu sou o perigo." body={["Walter passou cinquenta anos sendo invisível. Professor mal pago, pai diminuído, marido tolerado. Quando recebe um diagnóstico, não é a morte que o assusta — é morrer sem nunca ter existido.","Heisenberg não é uma transformação: é uma confissão. Tudo aquilo sempre esteve lá, apenas comprimido por décadas de medo da escassez.","Quando o Sobrevivente da Escassez se cansa de sobreviver, ele não busca paz. Ele busca poder. E o poder, sem cura, vira veneno."]}/>
      <CharacterPage number={10} total={TOTAL} archetype="Sobrevivente da Escassez" name="Jordan Belfort" movie="O Lobo de Wall Street · 2013" image={charJordan} quote="Eu prefiro ser rico e infeliz do que pobre e infeliz." body={["Jordan é o Sobrevivente da Escassez em sua versão eufórica. Onde Walter destrói para construir, Jordan constrói para anestesiar.","Cada milhão é uma dose. Cada festa, uma fuga. Ele não está celebrando — está tampando o som de algo antigo, abandonado, que ainda chora dentro dele.","É por isso que homens como ele nunca param. Parar é ouvir. E ouvir é o que a escassez nunca permitiu."]}/>
      <Page number={11} total={TOTAL} chapter="Arquétipo III" variant="purple"><p className="text-[10px] tracking-[0.5em] uppercase text-gold mb-6">Terceiro Arquétipo</p><h2 className="font-serif text-5xl md:text-7xl font-light leading-[0.95] mb-10">O Controlador<br/><em className="text-gold">Silencioso</em></h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Ele aprendeu, muito cedo, que o caos é fatal. Talvez tenha sido a casa que desabou. Talvez o pai que sumiu. Talvez a mãe que adoeceu. O que importa é o que ficou: a certeza de que, se ele não controlar tudo, tudo desaba.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Por isso ele se cala. Calcula. Antecipa. Vive três passos à frente — não por arrogância, mas por trauma. E, no fundo, está exausto.</p><PullQuote>Ele não controla porque é forte. Ele controla porque tem medo de descobrir o que sente.</PullQuote></Page>
      <CharacterPage number={12} total={TOTAL} archetype="Controlador Silencioso" name="Thomas Shelby" movie="Peaky Blinders · BBC" image={charShelby} quote="Em nome do diabo, no inferno serei eu o homem que serve a bebida." body={["Thomas voltou da guerra com um silêncio que ninguém em Birmingham sabia traduzir. Ele construiu um império não por ganância — por horror à vulnerabilidade.","Cada movimento dele é um algoritmo de sobrevivência. Cada afeto, uma exposição. Por isso o álcool. Por isso o ópio. Por isso a insônia.","O Controlador Silencioso não dorme. Quem dorme, sonha. E quem sonha, lembra."]}/>
      <CharacterPage number={13} total={TOTAL} archetype="Controlador Silencioso" name="Bruce Wayne" movie="The Dark Knight · 2008" image={charBatman} quote="Não é quem eu sou por dentro, mas o que eu faço, que me define." body={["Bruce viu a infância morrer em um beco. E a partir daquele instante, transformou luto em método. Disciplina em religião. Justiça em vingança vestida de virtude.","O Batman é o que sobra quando o Controlador Silencioso cresce sem ninguém para colocá-lo no colo. Ele não salva Gotham — ele tenta, todas as noites, salvar a criança que não conseguiu salvar os pais.","Toda vez que você assume responsabilidades que ninguém pediu, é o Batman dentro de você fazendo hora extra."]}/>
      <Page number={14} total={TOTAL} chapter="Arquétipo IV" variant="purple"><p className="text-[10px] tracking-[0.5em] uppercase text-gold mb-6">Quarto Arquétipo</p><h2 className="font-serif text-5xl md:text-7xl font-light leading-[0.95] mb-10">O Mago<br/><em className="text-gold">Fragmentado</em></h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Ele sabe coisas que não devia saber. Vê padrões que outros não veem. Sente o quarto antes de entrar. E essa sensibilidade — que poderia ser dom — virou peso, porque ninguém o ensinou a carregá-la.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">O Mago Fragmentado vive entre dois mundos: o que enxerga e o que finge enxergar para se encaixar. Essa cisão é a sua dor. E também, paradoxalmente, a sua porta.</p><PullQuote>O dom não foi dado para você usar contra o mundo. Foi dado para você usar a favor de si mesmo.</PullQuote></Page>
      <CharacterPage number={15} total={TOTAL} archetype="Mago Fragmentado" name="Stephen Strange" movie="Doctor Strange · Marvel" image={charStrange} quote="Você não pode vencer a morte. Você só pode lutar contra ela." body={["Stephen era um cirurgião brilhante que precisou perder as mãos para encontrar a alma. A queda dele não foi castigo — foi convocação.","O Mago Fragmentado precisa, quase sempre, de uma ruptura para acessar o próprio dom. Antes disso, ele usa a inteligência como armadura. Depois, como ofício.","Você já passou por uma queda que, hoje, você reconhece como o início de quem você é? Era ele."]}/>
      <CharacterPage number={16} total={TOTAL} archetype="Mago Fragmentado" name="Neo" movie="The Matrix · 1999" image={charNeo} quote="Eu sei que vocês estão aí. Eu posso senti-los." body={["Neo é a alma que sente o erro do sistema antes de poder nomeá-lo. Que vive a rotina sabendo, no corpo, que algo está errado — sem ter palavras para o que.","É o arquétipo de quem desconfia da própria vida. De quem acorda às três da manhã com uma pergunta sem dono. De quem busca sem saber o quê — apenas porque parar de buscar dói mais.","Quando a pílula vermelha aparece para Neo, ela não chega de fora. Ela chega como permissão para confiar no que ele já sabia."]}/>
      <Page number={17} total={TOTAL} chapter="Capítulo 09" variant="dark"><h2 className="font-serif text-4xl md:text-6xl font-light leading-tight mb-10">O Ciclo<br/><em className="text-gold">Invisível</em>.</h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Você releu este ebook e, em algum momento, sentiu um aperto. Pode ter sido em Harley. Pode ter sido em Walter. Pode ter sido em Bruce. Esse aperto não é coincidência: é reconhecimento.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">O ciclo invisível é o nome técnico para uma ferida que se repete. Não porque você é fraco. Mas porque o inconsciente prefere o conhecido — mesmo doloroso — ao desconhecido — mesmo libertador.</p><PullQuote>Padrão é destino com nome falso.</PullQuote><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">E o primeiro ato de liberdade é parar de chamar de azar aquilo que tem nome, raiz e história.</p></Page>
      <Page number={18} total={TOTAL} chapter="Capítulo 10" variant="purple"><h2 className="font-serif text-4xl md:text-6xl font-light leading-tight mb-10">O Que o Tarot<br/>Realmente <em className="text-gold">Revela</em>.</h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">O Tarot não prevê o futuro. Ele desenha o presente com tinta visível. Cada arcano é um arquétipo desenhado em imagem, e cada leitura é um espelho que devolve a você o que você já sabia — mas não tinha coragem de olhar.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Em minhas leituras, eu não trabalho com sorte. Eu trabalho com padrão. Identifico qual arquétipo está dirigindo a sua vida sem o seu consentimento — e devolvo a direção para você.</p><PullQuote>O Tarot não diz o que vai acontecer. Diz o que está acontecendo enquanto você não olha.</PullQuote></Page>
      <Page number={19} total={TOTAL} chapter="Capítulo 11" variant="dark"><h2 className="font-serif text-4xl md:text-6xl font-light leading-tight mb-10">O Ponto de<br/><em className="text-gold">Ruptura</em>.</h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Existe um momento, na vida de toda pessoa que desperta, em que ela não consegue mais fingir. O trabalho perdeu o sentido. O relacionamento ficou pequeno. O corpo começou a falar.</p><p className="font-serif text-lg md:text-xl leading-[1.8] mb-6 opacity-95">Esse é o ponto de ruptura. Não é o fim — é a primeira vez em muito tempo que o seu inconsciente conseguiu te alcançar. E ele só te alcança quando o silêncio dói mais do que a verdade.</p><PullQuote>Se você chegou até aqui, você já sabe. Falta apenas a coragem de nomear.</PullQuote><div className="mt-10 flex flex-col sm:flex-row flex-wrap gap-4"><CTA href="https://marymorgan-4-arquetipos.vercel.app/" label="Explorar Arquétipos"/><CTA href="https://marymorgan-relatos.vercel.app/" label="Ver Relatos"/></div></Page>
      <Page number={20} total={TOTAL} chapter="Convite Final" variant="dark"><div className="flex flex-col items-center text-center pt-10"><p className="text-[11px] tracking-[0.5em] uppercase text-gold mb-8">Última Página</p><h2 className="font-serif text-5xl md:text-7xl font-light leading-[1] mb-10 max-w-2xl">O seu padrão tem<br/><em className="text-gold">nome</em>.<br/>Pronta para descobrir?</h2><Ornament/><p className="font-serif text-lg md:text-xl leading-[1.8] max-w-xl opacity-90 mb-12">Em uma leitura comigo, identificamos o arquétipo que está conduzindo a sua vida — e abrimos a porta para o que vem depois dele.</p><div className="flex flex-col items-center gap-5 mb-16"><CTA href="https://marymorgan-tarot.vercel.app/" label="Decifrar Meu Padrão" variant="primary"/><CTA href="https://marymorgan.vercel.app/" label="Entrar na Experiência"/></div><div className="gold-divider w-32 mb-8"/><p className="font-serif italic text-base opacity-70 mb-12 max-w-md">"Você não precisa virar outra pessoa. Você só precisa parar de viver no lugar de quem você não é."</p><p className="text-[10px] tracking-[0.5em] uppercase text-gold">Mary Morgan</p><button onClick={handleDownload} disabled={downloading} className="no-print mt-16 inline-flex items-center gap-3 px-8 py-4 text-[11px] tracking-[0.35em] uppercase text-[oklch(0.12_0.005_280)] transition hover:scale-[1.02] disabled:opacity-60" style={{background:"var(--gradient-gold)",boxShadow:"var(--glow-gold)"}}><BookOpen className="h-4 w-4"/>{downloading?"Gerando PDF...":"Baixar Ebook em PDF"}</button></div></Page>
    </div>
  </main>;
}
